fixed checkstyle mistakes
mate-academy/checkstyle-intro pull request #150
Opened 2021-06-18 17:30 UTC by lavrivskyi

2021-08-12 06:18 UTC, Resci requested changes

2021-08-12 06:18 UTC, Resci commented on src/main/java/core/basesyntax/HelloWorld.java
> +    private int variable;
What does `variable` mean?

2021-08-12 06:18 UTC, Resci commented on src/main/java/core/basesyntax/HelloWorld.java
> +        StringBuilder result = new StringBuilder();
Good point!

2021-08-12 17:49 UTC, lavrivskyi commented on src/main/java/core/basesyntax/HelloWorld.java
> +    private int variable;
Changed to "currentYear"

2021-08-13 05:16 UTC, Resci requested changes

2021-08-13 05:16 UTC, Resci commented on src/main/java/core/basesyntax/HelloWorld.java
> +    private String helloMates;
```suggestion
    private String greeting;
```

2021-08-13 06:10 UTC, lavrivskyi commented on src/main/java/core/basesyntax/HelloWorld.java
> +    private String helloMates;
Fixed.

2021-08-13 10:53 UTC, Resci approved these changes

2024-08-13 19:26 UTC, closed without merging