added solution
mate-academy/checkstyle-intro pull request #213
Opened 2021-08-13 14:04 UTC by taras-oleksiuk

2021-08-13 14:34 UTC, Resci requested changes

2021-08-13 14:34 UTC, Resci commented on src/main/java/core/basesyntax/HelloWorld.java
> +    private String greeting = "";
```suggestion
    private String greeting;
```

2021-08-13 14:34 UTC, Resci commented on src/main/java/core/basesyntax/Model/Cat.java
> +                + ", ownerName='" + ownerName + '\'' + '}';
```suggestion
        return "Cat{ "
        		 + "age=" + age 
        		 + ", name='" + name + '\''
                 + ", ownerName='" + ownerName + '\'' + '}';
```

2021-08-13 14:34 UTC, Resci commented on src/main/java/core/basesyntax/Model/Dog.java
> +package core.basesyntax.model;
Назва пакету має співпадати з назвою папки

2021-08-13 14:47 UTC, taras-oleksiuk commented on src/main/java/core/basesyntax/HelloWorld.java
> +    private String greeting = "";
This has been fixed.

2021-08-13 14:47 UTC, taras-oleksiuk commented on src/main/java/core/basesyntax/Model/Cat.java
> +                + ", ownerName='" + ownerName + '\'' + '}';
This has been fixed.

2021-08-13 14:51 UTC, taras-oleksiuk commented on src/main/java/core/basesyntax/Model/Dog.java
> +package core.basesyntax.model;
I see "core.basesyntax.model." everywhere in IDE. I checked top code in classes: Dog, Cat, HelloWorld. Where & how I can fix it?

2021-08-16 08:37 UTC, MaliukDaria requested changes

2021-08-16 08:37 UTC, MaliukDaria commented on src/main/java/core/basesyntax/Model/Dog.java
> +package core.basesyntax.model;
yes, let's rename the package `Model` to `model`.

2021-08-18 18:41 UTC, closed without merging