Code Style Fix
mate-academy/checkstyle-intro pull request #687
Opened 2023-06-22 09:48 UTC by ConfusedSatlan

2023-06-23 06:53 UTC, KseniiaMakarova requested changes

2023-06-23 06:53 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/HelloWorld.java
> +    private int variable;
```suggestion
    private String message;
    private int year;
```

2023-06-26 06:09 UTC, KseniiaMakarova requested changes
code style failed
run `mvn clean package` and fix a mistake

2023-06-26 13:06 UTC, nacenik approved these changes
LGTM! 👍

2024-04-22 11:07 UTC, closed without merging